_grid_search_:
  "model/optimizer/lr": [ 0.001, 0.003, 0.01, 0.03, 0.1, 0.3, 1.0, 3.0, 10 ]  # learning_rate
  "model/drop": [ 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8 ]
_grid_search_repeat: 3
gpus: "[0] * 5"

cuda: "0"
model:
  dim: 32
  model: LGNRecModel
  n_layers: 3
  drop: 0.0
  decay: 0
  optimizer:
    lr: 1.0

DataLoader:
  batch_size: 8192

dataset:
  source: AB202Kdc3geCKGDataset # ML1MDataset # CiteULikeDataset / ML100KDataset
  filter_rating: 0
  split_mode: leave-one-out
  fast: True
SamplingSpace: BasedSamplingSpace
