_grid_search_:
  "model/optimizer/lr": [ 0.001, 0.003, 0.01, 0.03, 0.1, 0.3, 1.0, 3.0 ]  # learning_rate
  "model/drop": [ 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8 ]
_grid_search_repeat: 3
gpus: "[0] * 5"

cuda: "0"
name: BPR
model:
  dim: 32
  model: BPR
  drop: 0.5
  decay: 0
#  optimizer_class: Adam
  optimizer:
    lr: 0.3

#train:
#  print_eval: True
#  print_best: True

DataLoader:
  batch_size: 8192

dataset:
  source: AB202Kdc3ge # ML1MDataset # CiteULikeDataset / ML100KDataset
  target: AM143Kdc3ge # ML1MDataset # CiteULikeDataset / ML100KDataset
  filter_rating: 0
  split_mode: leave-one-out
#  split_mode: cold_user
  fast: True
SamplingSpace: BasedSamplingSpace

source_pretrain: https://github.com/JianhuanZhuo/dataset-package/releases/download/v0.0.2/BBM-hop1-connect-TransE-pretrained-0406-083906-52397731-for-AB202Kdc3ge.tar.zip
#target_pretrain: https://github.com/JianhuanZhuo/dataset-package/releases/download/v0.0.2/BBM-hop1-connect-TransE-pretrained-0406-083906-52397731-for-AM143Kdc3ge.tar.zip
#freeze_item: True