_grid_search_:
  "model/optimizer/lr": [ 0.03, 0.1, 0.3, 1.0, 3.0 ]  # learning_rate
#  "model/drop": [ 0, 0.1, 0.2, 0.3 ]
  "model/layer_slice": [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
  "model/n_layers": [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
  "model/k": [8, 16]
_grid_search_repeat: 3
gpus: "[0] * 5"

cuda: "0"
model:
  dim: 32
  model: AvgLGNRecModel
  n_layers: 8
  layer_slice: 8
  drop: 0.4
  decay: 0
  k: 1
  optimizer:
    lr: 0.3

DataLoader:
  batch_size: 8192

epochs: 100
evaluator_time: 1
#train:
#  print_eval: True
#  print_best: True

dataset:
  source: AB202Kdc3geAvg # ML1MDataset # CiteULikeDataset / ML100KDataset
  target: AM143Kdc3geAvg # ML1MDataset # CiteULikeDataset / ML100KDataset
  kg: BBMhop1ConnectKGDataset
  filter_rating: 0
  split_mode: leave-one-out
  fast: True
SamplingSpace: BasedSamplingSpace
