_grid_search_:
  "model/optimizer/lr": [ 0.1, 0.3, 1.0, 3.0 ]  # learning_rate
#  "model/drop": [ 0, 0.1, 0.2, 0.3 ]
  "model/layer_slice": [ 5, 6, 7, 8, 9, 10, 11, 12 ]
  "model/n_layers": [ 7, 8, 9, 10, 11, 12 ]
_grid_search_repeat: 1
gpus: "[0] * 5"

cuda: "0"
model:
  dim: 32
  model: LGNRecModel
  n_layers: 12
  layer_slice: 0
  drop: 0.0
  decay: 0
  optimizer:
    lr: 1.0

DataLoader:
  batch_size: 8192

epochs: 100
evaluator_time: 5
train:
  print_eval: True
  print_best: True

dataset:
  source: AB202Kdc3ge # ML1MDataset # CiteULikeDataset / ML100KDataset
  target: AM143Kdc3ge # ML1MDataset # CiteULikeDataset / ML100KDataset
  kg: BBMhop2KGDataset
  filter_rating: 0
  split_mode: leave-one-out
  fast: True
SamplingSpace: BasedSamplingSpace
