_grid_search_:
  "model/optimizer/lr": [ 0.003, 0.01, 0.03, 0.1, 0.3, 1.0, 3.0, 10 ]  # learning_rate
  "model/drop": [ 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8 ]
  "model/decay": [ 0, 0.003, 0.01, 0.03, 0.1, 0.3, 1.0, 3.0, 10 ]
_grid_search_repeat: 3
gpus: "[0] * 5"

cuda: "0"
name: BPR
model:
  dim: 32
  model: BPR
  drop: 0.1
  decay: 0
  optimizer:
    lr: 1.0


evaluator_args:
  stop_delay: 5
  use_stop: True
  eval_xs: [ 10, 100 ]
epochs: 100
evaluator_time: 1

DataLoader:
  batch_size: 8192

dataset:
  source: AB202Kdc3 # ML1MDataset # CiteULikeDataset / ML100KDataset
  filter_rating: 0
  split_mode: leave-one-out
  fast: True
SamplingSpace: BasedSamplingSpace
