# 实验唯一标识串
_grid_search_:
  "model/optimizer/lr": [ 0.1, 0.3, 1.0 ]  # learning_rate
  "model/drop": [ 0, 0.1, 0.2, 0.3, 0.4 ]
_grid_search_repeat: 1
gpus: "[0] * 5"

cuda: "0"
name: TransE
model:
  dim: 32
  model: TransE
  drop: 0.6
  decay: 0
  optimizer:
    lr: 1

DataLoader:
#  batch_size: 16384
  batch_size: 524288

epochs: 5
evaluator_time: 1
train:
  batch_tqdm: True
  print_eval: True

evaluator_args:
  best_save: True
  use_stop: True
  stop_delay: 2
  eval_xs: [ 3 ]

dataset:
  kg: bbmhop1connectkg # ML1MDataset # CiteULikeDataset / ML100KDataset
#  kg: BBMhop1Connect # ML1MDataset # CiteULikeDataset / ML100KDataset
  filter_rating: 0
  split_mode: leave-one-out
  fast: True
SamplingSpace: BasedSamplingSpace
